sudo: required
services:
  - docker

before_install:
  - docker build -t kuldeepadhikarimpf/docker-react -f Dockerfile.dev .

script:
  - docker run kuldeepadhikarimpf/docker-react npm run test -- --coverage
