version: '3.3'
services:
    web:
      restart: on-failure
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports:
         - "3000:3000"
      volumes:
        - /app/node_modules
        - .:/app
    tests:
        build:
          context: .
          dockerfile: Dockerfile.dev
        volumes:
          - /app/node_modules
          - .:/app
        command: ["npm","run","test"]

#docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app 813f4a40e8bd
#docker exec -it cbbd42f2a18b npm run test
